---
title: "FastFile Read Benchmark Analysis"
output:
  html_document:
    number_sections: TRUE
    toc: true
#    toc_float: true
    toc_depth: 2
    fig_width: 9
    fig_height: 7
    fig_caption: true
    includes:
      after_body: footer.html
params:
  current_file:
  previous_file:
  date: !r Sys.Date()
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(conflicts.policy = list(error = FALSE, warn = FALSE))
```

```{r}
source("fastfile.r")
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
library(hrbrthemes)
library(viridis)
library(scales)
library(gdata, include.only=c("humanReadable"))
```

```{r reading_results}
current <- load_results(params$current_file)

# If we are in comparision mode
previous <- if (!is.null(params$previous_file)) { load_results(params$previous_file) }
has_previous <- !is.null(previous)
```

# Overview

```{r overview}
p <- if (has_previous) {
    ggplot() +
      geom_violin(data=previous, aes(x=file_size_human, y=time), fill="#B12729", color="#B12729", alpha=0.8) +
      geom_violin(data=current, aes(x=file_size_human, y=time), fill="#56B4E9", color="#56B4E9", alpha=0.8)
  } else {
    ggplot() +
      geom_violin(data=current, aes(x=file_size_human, y=time), fill="#56B4E9", color="#56B4E9")
  }
p <- p +
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format(function(x) x, function(x) round(x, digits=2))) +
    theme_ipsum() +
    theme(legend.position="none") +
    coord_flip() + # This switch X and Y axis and allows to get the horizontal version
    ggtitle("Run time PDF per file size") +
    xlab("File Size") +
    ylab("Run Time [ms]")

p
```

This analysis has been run `r Sys.time()`.

Showing benchmark results for "_`r params$current_file`_" with `r nrow(current)` samples.  
`r if (has_previous) {
  sprintf("Comparing with results from _%s_ with %d samples.", params$previous_file, nrow(previous))
}`


# Mean and Median Run Time

```{r meanruntime, out.width=c('50%', '50%'), fig.show='hold'}
current_means <- aggregate_results(current, mean)
previous_means <- if (has_previous) { aggregate_results(previous, mean) }

p <- if (has_previous) {
    ggplot() + 
      geom_segment(data=previous_means, mapping=aes(x=file_size, y=time, xend=c(tail(file_size, n=-1), NA), yend=c(tail(time, n=-1), NA)), alpha=0.8, color="#B12729") +
      geom_point(data=previous_means, aes(x=file_size, y=time), shape=21, color="black", fill="#B12729", alpha=0.8, size=3) +
      geom_segment(data=current_means, mapping=aes(x=file_size, y=time, xend=c(tail(file_size, n=-1), NA), yend=c(tail(time, n=-1), NA)), color="#56B4E9") +
      geom_point(data=current_means, aes(x=file_size, y=time), shape=21, color="black", fill="#56B4E9", size=3)
  } else {
    ggplot() +
      geom_segment(data=current_means, mapping=aes(x=file_size, y=time, xend=c(tail(file_size, n=-1), NA), yend=c(tail(time, n=-1), NA)), color="#56B4E9") +
      geom_point(data=current_means, aes(x=file_size, y=time), shape=21, color="black", fill="#56B4E9", size=3)
  }
p <- p + 
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format(function(x) x, function(x) hr(x))) +
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format(function(x) x, function(x) round(x, digits=2))) +
    theme_ipsum() +
    ggtitle("Mean runtime") +
    xlab("File Size") +
    ylab("Mean Run Time [ms]")

p

current_medians <- aggregate_results(current, median)
previous_medians <- if (has_previous) { aggregate_results(previous, median) }

p <- if (has_previous) {
    ggplot() + 
      geom_segment(data=previous_medians, mapping=aes(x=file_size, y=time, xend=c(tail(file_size, n=-1), NA), yend=c(tail(time, n=-1), NA)), alpha=0.8, color="#B12729") +
      geom_point(data=previous_medians, aes(x=file_size, y=time), shape=21, color="black", fill="#B12729", alpha=0.8, size=3) +
      geom_segment(data=current_medians, mapping=aes(x=file_size, y=time, xend=c(tail(file_size, n=-1), NA), yend=c(tail(time, n=-1), NA)), color="#56B4E9") +
      geom_point(data=current_medians, aes(x=file_size, y=time), shape=21, color="black", fill="#56B4E9", size=3)
  } else {
    ggplot() +
      geom_segment(data=current_medians, mapping=aes(x=file_size, y=time, xend=c(tail(file_size, n=-1), NA), yend=c(tail(time, n=-1), NA)), color="#56B4E9") +
      geom_point(data=current_medians, aes(x=file_size, y=time), shape=21, color="black", fill="#56B4E9", size=3)
  }
p <- p + 
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format(function(x) x, function(x) hr(x))) +
    scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format(function(x) x, function(x) round(x, digits=2))) +
    theme_ipsum() +
    ggtitle("Median runtime") +
    xlab("File Size") +
    ylab("median Run Time [ms]")

p
```

# Individual File Sizes

```{r individual}
for (file_size in unique(current$file_size)) {
  current_fs <- current[current$file_size == file_size,]
  previous_fs <- if (has_previous) { previous[current$file_size == file_size,] } 
  title <- sprintf("Runtime density for file size %s", current_fs$file_size_human[1])

  p <- if (has_previous) {
    ggplot() +
      geom_density(data=previous_fs, aes(x=time), fill="#B12729", color="#B12729", alpha=0.8) +
      geom_vline(data=previous_fs, aes(xintercept=median(time)), color="#B12729", size=1) +
      geom_vline(data=previous_fs, aes(xintercept=mean(time)), color="#B12729", lty="dashed", size=1)
  } else {
    ggplot()
  }
  p <- p + 
    geom_density(data=current_fs, aes(x=time), fill="#56B4E9", color="#56B4E9", alpha=0.8) +
    geom_vline(data=current_fs, aes(xintercept=median(time)), color="#56B4E9", size=1) +
    geom_vline(data=current_fs, aes(xintercept=mean(time)), color="#56B4E9", lty="dashed", size=1) +
    ggtitle(title) +
    theme_ipsum() +
    xlab("Run Time [ms]") +
    ylab("Density")
    
  print(p)
}
```

