[package]
name = "fastfile"
version = "0.0.0"
authors = ["Lukas Pustina <lukas@pustina.de>"]
description = "Sequentially read and write files as fast as possible"
license = "MIT"
edition = "2018"

[dependencies]
