on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os.name }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
            allow_fail: true
          - name: macOS-latest
            allow_fail: false
          - name: windows-latest
            allow_fail: true
        rust:
          - 1.36.0
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{ matrix.rust }}
          command: check
          continue-on-error: ${{ matrix.os.allow_fail }}

