on: [push, pull_request]

name: CI

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os.name }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: ubuntu-latest
            allow_fail: true
          - name: macOS-latest
            allow_fail: false
        rust:
          - name: 1.36.0
            allow_fail: false
          - name: stable
            allow_fail: false
          - name: beta
            allow_fail: true
          - name: nightly
            allow_fail: true

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust.name }}
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          toolchain: ${{ matrix.rust.name }}
          command: check
          continue-on-error: ${{ matrix.os.allow_fail || matrix.rust.allow_fail }}

